# Generated by Django 4.2.5 on 2023-10-30 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=200, null=True)),
                ("overview", models.CharField(max_length=2000, null=True)),
                ("prepration", models.CharField(max_length=2000, null=True)),
                ("price", models.CharField(max_length=200, null=True)),
                ("age_group", models.CharField(blank=True, max_length=10, null=True)),
                ("duration", models.CharField(max_length=2000, null=True)),
            ],
        ),
    ]
