# Generated by Django 4.2.5 on 2023-10-30 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0002_item"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="done",
            field=models.BooleanField(default=False),
        ),
    ]
